import logging
from urllib.parse import quote
from scrapers.base import BaseScraper, PriceData

logger = logging.getLogger(__name__)

STORE_WHATSAPP = "https://wa.me/5519998552666"

# (nome_com_marca, preco_5ml_brl) — catálogo Maio/2026, preço de referência 5ml
CATALOG = [
    # ── FEMININOS IMPORTADOS ──────────────────────────────────────────────────
    ("Coco Mademoiselle - Chanel", 78.0),
    ("Devotion Feminino - Dolce & Gabbana", 60.0),
    ("La Bomba - Carolina Herrera", 62.0),
    ("Light Blue Feminino - Dolce & Gabbana", 44.0),
    ("Classique - Jean Paul Gaultier", 45.0),
    ("Dylan Turquoise - Versace", 45.0),
    ("Divine Elixir - Jean Paul Gaultier", 60.0),
    ("Sí Passione - Giorgio Armani", 50.0),
    ("My Way EDP - Giorgio Armani", 55.0),
    ("La Belle Paradise Garden Feminino - Jean Paul Gaultier", 55.0),
    ("212 Heroes Forever Young Feminino - Carolina Herrera", 60.0),
    ("212 VIP Rosé Elixir - Carolina Herrera", 59.0),
    ("La Vie est Belle - Lancôme", 50.0),
    ("Idôle Eau de Toilette - Lancôme", 50.0),
    ("Libre - Yves Saint Laurent", 59.0),
    ("English Pear & Freesia - Jo Malone", 75.0),
    ("L'Interdit - Givenchy", 62.0),
    ("Valentino Donna Born in Roma - Valentino", 71.0),
    ("L'eau D'Issey Feminino - Issey Miyake", 49.0),
    ("Good Girl Blush - Carolina Herrera", 52.0),
    ("Omnia Crystalline - Bvlgari", 60.0),
    ("Cheap and Chic - Moschino", 35.0),
    ("Cheap and Chic I Love Love - Moschino", 35.0),
    ("Omnia Amethyste - Bvlgari", 60.0),
    ("J'Adore EDP - Dior", 58.0),
    ("La Vie est Belle L'Elixir - Lancôme", 55.0),
    ("La Vie est Belle Rose Extraordinaire - Lancôme", 55.0),
    ("Prada Paradoxe - Prada", 65.0),
    ("Miss Dior Eau de Parfum - Dior", 60.0),
    ("Flower by Kenzo - Kenzo", 50.0),
    ("Montblanc Signature - Montblanc", 50.0),
    ("The Only One - Dolce & Gabbana", 55.0),
    ("Eternity Feminino - Calvin Klein", 40.0),
    ("Acqua di Gioia - Giorgio Armani", 48.0),
    ("Euphoria - Calvin Klein", 40.0),
    ("CH Woman - Carolina Herrera", 50.0),
    ("Dior Addict Eau de Parfum - Dior", 65.0),
    ("Pour Femme - Dolce & Gabbana", 45.0),
    ("Verveine Feminino - L'Occitane en Provence", 45.0),
    ("Eternity Aromatic Essence Feminino - Calvin Klein", 35.0),
    ("My Way Néctar - Giorgio Armani", 55.0),
    ("Rose Tangerine - Chloé", 59.0),
    ("Fresh Couture - Moschino", 35.0),
    ("Versense - Versace", 45.0),
    ("Funny! - Moschino", 30.0),
    ("Light Blue EDP Feminino - Dolce & Gabbana", 55.0),
    ("Scandal EDP - Jean Paul Gaultier", 65.0),
    ("Bright Crystal - Versace", 55.0),
    ("Q by Dolce & Gabbana - Dolce & Gabbana", 59.0),
    ("Pure Musc - Narciso Rodriguez", 50.0),
    ("Un Jardin Sur le Nil Feminino - Hermès", 67.0),
    # ── MASCULINOS IMPORTADOS ─────────────────────────────────────────────────
    ("Vibrato - Sospiro", 119.0),
    ("Myslf - Yves Saint Laurent", 55.0),
    ("Bvlgari Pour Homme - Bvlgari", 55.0),
    ("Prada Paradigme - Prada", 60.0),
    ("Light Blue Masculino - Dolce & Gabbana", 45.0),
    ("Versace Eros Energy - Versace", 45.0),
    ("Acqua di Giò Profondo EDT - Giorgio Armani", 50.0),
    ("Versace Eros EDT - Versace", 42.0),
    ("Polo 67 EDP - Ralph Lauren", 35.0),
    ("Ralph's Club EDT - Ralph Lauren", 45.0),
    ("Boss Bottled Bold Citrus - Hugo Boss", 45.0),
    ("L'eau d'Issey EDP Masculino - Issey Miyake", 60.0),
    ("Boss Bottled Absolu - Hugo Boss", 55.0),
    ("212 Men VIP MTV - Carolina Herrera", 45.0),
    ("Prada L'Homme EDT - Prada", 55.0),
    ("Gentleman Society Extreme - Givenchy", 50.0),
    ("Boss Bottle Elixir - Hugo Boss", 55.0),
    ("Chrome - Azzaro", 35.0),
    ("Coach Green - Coach", 45.0),
    ("Y EDT - Yves Saint Laurent", 50.0),
    ("Le Beau Le Parfum - Jean Paul Gaultier", 50.0),
    ("Acqua di Giò EDP - Giorgio Armani", 45.0),
    ("Le Beau EDT - Jean Paul Gaultier", 45.0),
    ("Issey Miyake Vetiver Intense - Issey Miyake", 50.0),
    ("Terre d'Hermès Eau Givrée - Hermès", 60.0),
    ("Phantom EDT - Rabanne", 40.0),
    ("Le Male Le Parfum - Jean Paul Gaultier", 45.0),
    ("Bvlgari Man Glacial Essence - Bvlgari", 55.0),
    ("Dior Homme - Dior", 60.0),
    ("Valentino Uomo Born in Roma - Valentino", 55.0),
    ("Montblanc Explorer - Montblanc", 40.0),
    ("Bleu de Chanel Parfum - Chanel", 75.0),
    ("Pure XS - Rabanne", 50.0),
    ("Sauvage EDP - Dior", 60.0),
    ("Encre Noire - Lalique", 45.0),
    ("Bleu de Chanel EDT - Chanel", 65.0),
    ("Allure Homme Edition Blanche - Chanel", 70.0),
    ("Armani Code EDT - Giorgio Armani", 50.0),
    ("Polo Sport - Ralph Lauren", 30.0),
    ("L'eau Bleue D'Issey - Issey Miyake", 40.0),
    ("Versace Man Eau Fraiche - Versace", 35.0),
    ("Boss Bottled EDT - Hugo Boss", 35.0),
    ("Terre D'Hermès - Hermès", 65.0),
    ("Luna Rossa - Prada", 55.0),
    ("Bvlgari Aqva Pour Homme - Bvlgari", 55.0),
    ("Bvlgari Man in Black EDP - Bvlgari", 60.0),
    ("Eternity Aromatic Essence Masculino - Calvin Klein", 40.0),
    ("The One EDT - Dolce & Gabbana", 55.0),
    ("Bleu Noir Parfum - Narciso Rodriguez", 65.0),
    ("Y EDP - Yves Saint Laurent", 55.0),
    ("Dior Homme Cologne - Dior", 60.0),
    ("Bvlgari Man Rain Essence - Bvlgari", 50.0),
    ("Un Jardin Sur le Nil Masculino - Hermès", 65.0),
    ("Issey Miyake Solar Lavender - Issey Miyake", 45.0),
    ("Acqua di Giò Profondo Parfum - Giorgio Armani", 50.0),
    ("La Nuit de L'Homme - Yves Saint Laurent", 50.0),
    ("The Most Wanted - Azzaro", 45.0),
    ("Wanted - Azzaro", 40.0),
    ("Polo 67 EDT - Ralph Lauren", 37.0),
    ("Versace Dylan Blue - Versace", 45.0),
    ("Versace Pour Homme - Versace", 45.0),
    ("Light Blue Eau Intense Masculino - Dolce & Gabbana", 55.0),
    ("212 Men NYC - Carolina Herrera", 35.0),
    ("Issey Miyake Intense - Issey Miyake", 40.0),
    ("Vetiver Musc - Narciso Rodriguez", 60.0),
    ("Le Male Elixir - Jean Paul Gaultier", 50.0),
    ("212 Heroes Forever Young Masculino - Carolina Herrera", 50.0),
    ("Verbena Masculino - L'Occitane en Provence", 28.0),
    ("Light Blue EDP Masculino - Dolce & Gabbana", 52.0),
    ("Mercedes Benz Club Black - Mercedes-Benz", 31.0),
    ("Hugo for Men - Hugo Boss", 35.0),
    ("L'eau D'Issey Pour Homme - Issey Miyake", 35.0),
    ("Bleu Noir EDP - Narciso Rodriguez", 60.0),
    ("Supremacy Collector's Edition - Afnan", 40.0),
    ("Dior Homme Intense - Dior", 65.0),
    ("Acqua di Giò Elixir - Giorgio Armani", 90.0),
    ("Devotion Masculino - Dolce & Gabbana", 60.0),
    ("Bad Boy Sparkling Ice - Carolina Herrera", 45.0),
    ("Le Beau Paradise Garden - Jean Paul Gaultier", 50.0),
    ("Acqua di Giò Parfum - Giorgio Armani", 50.0),
    ("Gentleman Réservée Privée - Givenchy", 55.0),
    ("Ralph's Club New York - Ralph Lauren", 55.0),
    ("H24 - Hermès", 60.0),
    ("Acqua di Giò Profondo EDP - Giorgio Armani", 45.0),
    ("Artisan Pure - John Varvatos", 45.0),
    ("Coach for Men - Coach", 45.0),
    ("212 VIP Black - Carolina Herrera", 40.0),
    ("Nuit D'Issey - Issey Miyake", 50.0),
    ("CH Men - Carolina Herrera", 45.0),
    ("Starwalker - Montblanc", 40.0),
    ("Le Male EDT - Jean Paul Gaultier", 40.0),
    ("Platinum Egoiste - Chanel", 65.0),
    ("Acqua di Giò EDT - Giorgio Armani", 40.0),
    ("Declaration - Cartier", 65.0),
    ("Sauvage Parfum - Dior", 70.0),
    ("Polo Blue EDT - Ralph Lauren", 40.0),
    ("The One EDP - Dolce & Gabbana", 60.0),
    ("Bleu Noir EDT - Narciso Rodriguez", 50.0),
    ("Ombré Leather - Tom Ford", 120.0),
    ("K EdP - Dolce & Gabbana", 55.0),
    ("Hugo Reversed - Hugo Boss", 35.0),
    ("Ralph's Club EDP - Ralph Lauren", 45.0),
    ("CK One - Calvin Klein", 25.0),
    ("Eternity EDP Masculino - Calvin Klein", 40.0),
    ("Mojito Obsession - Gulf Orchid", 31.0),
    ("Stronger With You Intensely - Giorgio Armani", 55.0),
    ("Luna Rossa Ocean EDT - Prada", 60.0),
    # ── ÁRABES ───────────────────────────────────────────────────────────────
    ("Hawas Kobra - Rasasi", 37.0),
    ("Hawas Black - Rasasi", 33.0),
    ("Hawas Verde - Rasasi", 34.0),
    ("Hawas Ice - Rasasi", 32.0),
    ("Yara - Lattafa", 26.0),
    ("Atheeri - Lattafa", 42.0),
    ("Khamrah - Lattafa", 25.0),
    ("Khamrah Dukhan - Lattafa", 27.0),
    ("Khamrah Qawah - Lattafa", 29.0),
    ("Fakhar Rosé - Lattafa", 29.0),
    ("Eclaire Pistache - Lattafa", 28.0),
    ("Eclaire Banoffi - Lattafa", 28.0),
    ("Art of Universe - Lattafa", 28.0),
    ("Art of Arabia I - Lattafa", 28.0),
    ("Asad Zanzibar - Lattafa", 25.0),
    ("Haya - Lattafa", 29.0),
    ("Tres Nuit - Armaf", 30.0),
    ("Club de Nuit Sillage - Armaf", 27.0),
    ("Club de Nuit Milestone - Armaf", 27.0),
    ("Club de Nuit Iconic - Armaf", 28.0),
    ("9PM Rebel - Afnan", 32.0),
    ("9AM Dive - Afnan", 25.0),
    ("Turathi Blue - Afnan", 32.0),
    ("Turathi Electric - Afnan", 32.0),
    ("Aether Extrait - French Avenue", 40.0),
    ("Vulcan Feu - French Avenue", 40.0),
    ("Safari Breeze - French Avenue", 37.0),
    ("Aromatix Teas Me - French Avenue", 40.0),
    ("Pacific Aura - Rayhaan", 35.0),
    ("Itália - Rayhaan", 35.0),
    ("Rayhaan Aquática - Rayhaan", 34.0),
    ("Habibi Prince - Bidaya", 33.0),
    ("Aisha Queen - Bidaya", 30.0),
    ("Elliur - Bidaya", 33.0),
    ("Delilah - Maison Alhambra", 26.0),
    ("Philos Messenger - Maison Alhambra", 25.0),
    ("Voux Zingy - Paris Corner", 29.0),
    ("Shiyaaka Snow - Khadlaj", 25.0),
    ("Fahed - Niche Avenue", 35.0),
    ("Ameer - Niche Avenue", 30.0),
    ("Hadi - Niche Avenue", 35.0),
    # ── CONTRATIPOS ──────────────────────────────────────────────────────────
    ("Mare di Luci - Nuancielo", 20.0),
    ("Like a Boss - Nuancielo", 20.0),
    ("Domus - Nuancielo", 20.0),
    ("Octano - Nuancielo", 20.0),
    ("Alpha Leggera - Nuancielo", 20.0),
    ("Hezron - Nuancielo", 20.0),
    ("Fjord - Nuancielo", 20.0),
    ("Caribbean - Nuancielo", 20.0),
    ("Italian Soul - Nuancielo", 20.0),
    ("Edah - Nuancielo", 20.0),
    ("Mondé Paralelle - Nuancielo", 20.0),
    ("Dream On Infinite - Nuancielo", 20.0),
    ("Ayael - Nuancielo", 20.0),
    ("Royal Acqua - Nuancielo", 20.0),
    ("Oud Tropicale - Nuancielo", 20.0),
    ("Lemon & Neroli - Nuancielo", 20.0),
    ("Angels Lux - Nuancielo", 20.0),
    ("Efrate - Nuancielo", 20.0),
    ("Royal Garden - Nuancielo", 20.0),
    ("Ezodus Extreme - Nuancielo", 20.0),
    ("Hills - Nuancielo", 20.0),
    ("Mead - Nuancielo", 20.0),
    ("Fairy - Nuancielo", 20.0),
    ("Blue Celestia - Nuancielo", 20.0),
    ("Alpha Blanche - Nuancielo", 20.0),
    ("Real King Absolu - Nuancielo", 20.0),
    ("Gálata - Nuancielo", 20.0),
    ("Supremacy - Nuancielo", 20.0),
    ("Dolce Bianco - Nuancielo", 20.0),
    ("Magna - Nuancielo", 20.0),
    ("Jocker - Nuancielo", 20.0),
    ("Sunshine - Nuancielo", 20.0),
    ("Reveur - Nuancielo", 20.0),
    ("Aura Elite - Nuancielo", 20.0),
    ("Orange & Vetiver - Nuancielo", 20.0),
    ("Ner Tamid - Nuancielo", 20.0),
    ("Rose Fairy - Nuancielo", 20.0),
    ("Everest - Nuancielo", 20.0),
    ("Enoch - Nuancielo", 20.0),
    ("Mystic Fairy - Nuancielo", 20.0),
    ("Creme Pistachio - Nuancielo", 20.0),
    ("Zion Sanctus - Nuancielo", 20.0),
    ("Éclat Vanille - Nuancielo", 20.0),
    ("Evodia Extrait - Nuancielo", 20.0),
    ("Ultramare - Maison Viegas", 20.0),
    ("Elite Pour Homme - Maison Viegas", 20.0),
    ("Heaven - Maison Viegas", 20.0),
    ("Le Paradise - Maison Viegas", 20.0),
    ("Summer Cítrus - Maison Viegas", 20.0),
    ("Un Jardin - Maison Viegas", 20.0),
    ("Narcotique Flower - Maison Viegas", 20.0),
    ("Black Noire Sport - Maison Viegas", 20.0),
    ("Grand Tygar - Maison Viegas", 20.0),
    ("Corsário - Maison Viegas", 20.0),
    ("Legacy - Maison Viegas", 20.0),
    ("Gin Tonic - Maison Viegas", 20.0),
    ("Corleone - Maison Viegas", 20.0),
    ("Jazz Master - Maison Viegas", 20.0),
    ("Vetiver Absoluto - Maison Viegas", 20.0),
    ("The Sexy Elixir - Maison Viegas", 20.0),
    ("Legend - Maison Viegas", 20.0),
    ("Montecristo - Maison Viegas", 20.0),
    ("Amber Absolu - Maison Viegas", 20.0),
    ("Duquesa - Maison Viegas", 20.0),
    ("Cactus - JA Essence de la Vie", 20.0),
    ("Chá - JA Essence de la Vie", 20.0),
    ("Monkey - JA Essence de la Vie", 20.0),
    ("Fabulous Charm - JA Essence de la Vie", 20.0),
    ("Bull 21 - JA Essence de la Vie", 20.0),
    ("Brandy Maçã - JA Essence de la Vie", 20.0),
    ("Sinfonia - JA Essence de la Vie", 20.0),
    ("Meteorite Overdose - JA Essence de la Vie", 20.0),
    ("Sea - JA Essence de la Vie", 20.0),
    ("Gany - JA Essence de la Vie", 20.0),
    ("Valent - JA Essence de la Vie", 20.0),
    ("Macedônia - JA Essence de la Vie", 20.0),
    ("Réplica - JA Essence de la Vie", 20.0),
    ("Amalfi - JA Essence de la Vie", 20.0),
    ("Celestial Stone - In the Box", 20.0),
    ("Lemon Luxs - In the Box", 20.0),
    ("Infinite Horizon - In the Box", 20.0),
    ("Essenza Nobile - In the Box", 20.0),
    ("Versus Pour Homme - In the Box", 20.0),
    ("Profumo di Salerno - In the Box", 20.0),
    ("Fresh and Senses - In the Box", 20.0),
    ("Earthy Icy - In the Box", 20.0),
    ("Lemon Vanilla & Wood - In the Box", 20.0),
    ("Flow Vibes - In the Box", 20.0),
    ("Citrus Craving - In the Box", 20.0),
    ("Envoy - In the Box", 20.0),
    ("Dominus Elixir - In the Box", 20.0),
    ("Pride L'Homme - In the Box", 20.0),
    ("Enigma Blend - In the Box", 20.0),
    ("Mystic Newlands - In the Box", 20.0),
    ("Lumen Blue - In the Box", 20.0),
    ("Fire Snake - In the Box", 20.0),
    ("Irish Green Man - In the Box", 20.0),
    ("Bluish Light - In the Box", 20.0),
    ("La Belle Fleur - In the Box", 20.0),
    ("Real Lignum - In the Box", 20.0),
    ("Dark Water - In the Box", 20.0),
    ("Taylor Made - In the Box", 20.0),
    ("Turim - In the Box", 20.0),
    ("Me and I Absolu - In the Box", 20.0),
    ("Lux de Vie - In the Box", 20.0),
    ("Soft Splendor - In the Box", 20.0),
    ("Salt Crystal - In the Box", 20.0),
    ("Dévoile - In the Box", 20.0),
    ("Blanche Exquise - In the Box", 20.0),
    ("Makathén - In the Box", 20.0),
    ("Lord Town - In the Box", 20.0),
    ("Liberté Absolu - In the Box", 20.0),
    ("Leather - Par Fun", 20.0),
    ("Electric Dream - Par Fun", 20.0),
    ("Bomb Exteme - Par Fun", 20.0),
    ("Love Expresso - Par Fun", 20.0),
    ("Italian Blue - Par Fun", 20.0),
    ("Light Intense - Par Fun", 20.0),
    ("Profondo - Par Fun", 20.0),
    ("Erol - Par Fun", 20.0),
    ("Toro - Par Fun", 20.0),
    ("Spicy - Par Fun", 20.0),
    ("Greenly - Par Fun", 20.0),
    ("Istambul - Par Fun", 20.0),
    ("Malta - Thera", 20.0),
    ("Brasili - Thera", 20.0),
    ("Amórgos - Thera", 20.0),
    ("Amórgos Absolu - Thera", 20.0),
    ("Vinci - Thera", 20.0),
    ("Taurus - Thera", 20.0),
    ("Effie - Thera", 20.0),
    ("Madrid - Thera", 20.0),
    ("Nikaia - Thera", 20.0),
    ("Bose - Thera", 20.0),
    ("Gigio - Thera", 20.0),
    ("Volcano Gold - Thera", 20.0),
    ("Aspen - Thera", 20.0),
    ("Soniere - Thera", 20.0),
    ("Reserve - Thera", 20.0),
    ("Effervescent - Lab8", 20.0),
    # ── NICHO NACIONAL e GRANADO ──────────────────────────────────────────────
    ("Bólido - Sapientiae Niche", 30.0),
    ("Caos - Sapientiae Niche", 30.0),
    ("Seabeast - Sapientiae Niche", 30.0),
    ("Black Mamba - Sapientiae Niche", 30.0),
    ("Fortuna - Sapientiae Niche", 30.0),
    ("S.S. Marítima - Sapientiae Niche", 30.0),
    ("Heroin - Sapientiae Niche", 30.0),
    ("Above All - Sapientiae Niche", 30.0),
    ("Graal - Sapientiae Niche", 30.0),
    ("Capuccino - Condé", 65.0),
    ("Caipi d'Argent - Condé", 65.0),
    ("Cologne Bleue - Condé", 65.0),
    ("L'eau de Fruits - Condé", 65.0),
    ("Bois d'Orange - Condé", 65.0),
    ("Tabac d'Or - Condé", 65.0),
    ("Vanille Bourbon - Condé", 65.0),
    ("Ambre Beige - Condé", 65.0),
    ("2.10 (limão taiti - gengibre - moscow mule) - Amyi", 65.0),
    ("2.11 (muguet - cashmere - complexo musk) - Amyi", 65.0),
    ("5.22 (baunilha defumada - tabaco caramelizado - ládano absoluto) - Amyi", 65.0),
    ("3.16 (figo - açafrão negro - âmbar mineral) - Amyi", 65.0),
    ("Amyi I (toranja - greenal - âmbar branco) - Amyi", 65.0),
    ("Amyi IX (bergamota - pimenta sichuan - gin tônica) - Amyi", 65.0),
    ("2.13 (íris negra - ruibarbo - sândalo) - Amyi", 65.0),
    ("2.14 (mandarina coeur - gotas de orvalho - jasmin absoluto) - Amyi", 65.0),
    ("Amyi VIII (tomilho vermelho - erva flouve - camurça branca) - Amyi", 65.0),
    ("Wabi - Sorry not Sorry", 65.0),
    ("Sumo - Sorry not Sorry", 65.0),
    ("Sépia - Sorry not Sorry", 65.0),
    ("Nostalgic Velvet - Sorry not Sorry", 65.0),
    ("Citron Soleil - Amberfig", 65.0),
    ("Bamboo & Green Tea - Amberfig", 65.0),
    ("Granado Fervo Intenso - Granado", 33.0),
    ("Granado Yes, Nós Temos Banana! - Granado", 33.0),
    ("Granado Amazônico - Granado", 33.0),
    ("Granado Apotecário - Granado", 33.0),
    ("Granado Boemia - Granado", 33.0),
    ("Granado Citrus Brasilis - Granado", 33.0),
    ("Granado Esplendor - Granado", 33.0),
    ("Granado Infusão Botânica - Granado", 33.0),
    ("Granado Elixir 1870 - Granado", 33.0),
    ("Granado Nostalgia - Granado", 33.0),
    ("Granado Imperial - Granado", 33.0),
    ("Granado Bossa - Granado", 33.0),
    ("Granado Carioca - Granado", 33.0),
    ("Granado Couro - Granado", 33.0),
    ("Granado Suede - Granado", 33.0),
    ("Granado Neroli - Granado", 33.0),
    ("Phebo Perfume Isolda Cajueiro - Phebo", 33.0),
]


class AlbergariaScraper(BaseScraper):
    store_name = "Fabrício Albergaria"
    store_slug = "albergaria"
    base_url = STORE_WHATSAPP

    def scrape(self):
        for entry, price in CATALOG:
            if " - " in entry:
                clean_name, brand = entry.rsplit(" - ", 1)
                clean_name = clean_name.strip()
                brand = brand.strip()
            else:
                clean_name = entry
                brand = None

            url = f"{STORE_WHATSAPP}?text={quote(entry)}"
            self.result.products.append(PriceData(
                name=clean_name,
                brand=brand,
                url=url,
                price=price,
                image_url=None,
                volume_ml=5,
                in_stock=True,
                category="perfume",
                tipo="decant",
            ))

        logger.info(f"[albergaria] {len(self.result.products)} produtos carregados do catálogo estático")
        return self.result
